apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
        service: order
    spec:
      # initContainers:
      #   - name: db-check
      #     image: busybox:1.28
      #     command: ['sh', '-c', 'until nslookup db; do echo waiting for db; sleep 10; done;']
      containers:
        - name: order
          image: asadlive84/order:1.0.0
          env:
            - name: APPLICATION_PORT
              value: "3000"
            - name: PAYMENT_SERVICE_URL
              value: "payment:30001"
            - name: DATA_SOURCE_URL
              value: "host=db user=root password=verysecretpass dbname=order port=5432 sslmode=disable TimeZone=Asia/Dhaka"
            - name: ENV
              value: "development"


---
apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    service: order
spec:
  selector:
    service: order
  type: LoadBalancer   # Change to LoadBalancer for an external IP
  ports:
    - name: grpc
      port: 3000
      protocol: TCP
      targetPort: 3000





