apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      # initContainers:
      #   - name: db-check
      #     image: busybox:1.28
      #     command: ['sh', '-c', 'until nslookup db; do echo waiting for db; sleep 10; done;']
      containers:
        - name: payment
          image: asadlive84/payment:1.0.0
          env:
            - name: APPLICATION_PORT
              value: "3001"
            - name: DATA_SOURCE_URL
              value: "host=db user=root password=verysecretpass dbname=order port=5432 sslmode=disable TimeZone=Asia/Dhaka"
            - name: ENV
              value: "development"


---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    service: payment
spec:
  clusterIP: clusterIP
  selector:
    service: payment
  ports:
    - name: grpc
      port: 3001
      protocol: TCP
      targetPort: 3001

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: selfsigned-issuer
  name: payment
spec:
  rules:
    - http:
        paths:
          - path: /Payment
            pathType: Prefix
            backend:
              service:
                name: payment
                port:
                  number: 3001
  tls:
    - hosts:
        - ingress.local

