apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
        service: payment
    spec:
      # initContainers:
      #   - name: db-check
      #     image: busybox:1.28
      #     command: ['sh', '-c', 'until nslookup db; do echo waiting for db; sleep 10; done;']
      containers:
        - name: payment
          image: asadlive84/payment:1.0.0
          env:
            - name: APPLICATION_PORT
              value: "30001"
            - name: DATA_SOURCE_URL
              value: "host=db user=root password=verysecretpass dbname=order port=5432 sslmode=disable TimeZone=Asia/Dhaka"
            - name: ENV
              value: "development"


---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    service: payment
spec:
  selector:
    service: payment
  ports:
    - name: grpc
      port: 30001
      protocol: TCP
      targetPort: 30001



